# Generated by Django 4.2.7 on 2026-08-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sales', models.FloatField()),
                ('COGS', models.FloatField()),
                ('marketing_expenses', models.FloatField()),
                ('other_expenses', models.FloatField()),
            ],
            options={
                'db_table': 'Accounting',
                'managed': False,
            },
        ),
    ]
