# Generated by Django 4.2.7 on 2026-08-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sales', models.FloatField()),
                ('COGS', models.FloatField()),
                ('marketing_expenses', models.FloatField()),
                ('other_expenses', models.FloatField()),
            ],
            options={
                'db_table': 'Accounting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('name', models.TextField(unique=True)),
                ('product_code', models.IntegerField(unique=True)),
                ('is_coffee', models.BooleanField()),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
                ('market', models.CharField(max_length=4)),
                ('market_size', models.CharField(max_length=15)),
                ('store_code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Stores',
                'managed': False,
            },
        ),
    ]
